# Generated by Django 4.2.3 on 2023-08-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='tagged_class',
            new_name='tagged_stories',
        ),
    ]
